# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180311_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_bank_account',
            new_name='bank_account',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_highscore',
            new_name='highscore',
        ),
    ]
