# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bitcoins', models.DecimalField(decimal_places=8, max_digits=15)),
                ('in_game_currency', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountToCollectible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=17)),
                ('name', models.CharField(max_length=127)),
                ('image', models.ImageField(upload_to='collectibles/')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccounttocollectible',
            name='collectible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.Collectible'),
        ),
    ]
