# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_auto_20180311_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='_bitcoins',
            new_name='bitcoins',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='_in_game_currency',
            new_name='in_game_currency',
        ),
    ]
